// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/cosmetice-naturale",

  metadata: {
    title: "Ghid de cosmetice naturale | PerfuMaria das Ervas",
    description:
      "80 de rețete de cosmetice 100% naturale pe care să le prepari acasă. Formule testate și validate, ideale pentru uz personal sau pentru a-ți lansa propria afacere.",
  },

  hero: {
    headlineLine1: "80 de rețete de",
    headlineHighlight: "COSMETICE NATURALE",
    subheadline:
      "Ai acces la rețete secrete de cosmetice 100% naturale pe care le poți crea chiar în confortul casei tale! Formule testate și dovedite, perfecte pentru uz personal sau pentru a pune bazele propriei afaceri.",
    cta: "VREAU ACCES ACUM!",
    imageAlt: "Ghid de cosmetice naturale",
    timerLabels: {
      days: "Zile",
      hours: "Ore",
      minutes: "Minute",
      seconds: "Secunde",
    },
  },

  story: {
    text: "Îți ofer acum un ghid practic, la obiect, fără complicații inutile, dar extrem de sigur, pentru a-ți crea acasă cosmetice 100% naturale. Fără să cheltuiești o avere, fără să depinzi de mii de ingrediente – și cu posibilitatea de a le folosi pentru tine, de a le oferi celor dragi sau chiar de a le vinde, dacă vrei să-ți creezi o nouă sursă de venit!",
    imageAlt: "Cosmetice naturale",
  },

  recipeList: {
    headline: "Descoperă cele",
    headlineHighlight: "80 de rețete,",
    headlineSuffix: "la care vei avea acces prin Ghidul de cosmetice naturale:",
    cta: "LE VREAU!",
    col1: [
      "Cremă de corp calmantă",
      "Cremă de corp cu pantenol",
      "Loțiune de corp revigorantă",
      "Cremă-sufleu de corp",
      "Unt de corp cu urucum",
      "Unt de corp solid",
      "Ulei de corp",
      "Ulei terapeutic pentru pete și vergeturi",
      "Ulei de corp bifazic",
      "Loțiune naturală pentru bronz",
      "Săpun lichid de corp",
      "Gel de duș",
      "Săpun solid de corp cu SCI",
      "Săpun solid de corp tradițional",
      "Săpun cremă hidratant",
      "Săpun exfoliant de corp (Body Scrub)",
      "Exfoliant de corp",
      "Exfoliant de corp cu făină de migdale",
      "Iluminator natural de corp",
      "Spray de corp (Body Splash)",
      "Cremă de față cu vitamina C",
      "Cremă de față after-sun cu lavandă",
      "Cremă de față cu argilă",
      "Loțiune facială hidratantă cu iasomie",
      "Ulei uscat pentru față (Dry Oil)",
      "Săpun lichid de față",
      "Spumă de curățare pentru față",
      "Ser facial pentru ten uscat și sensibil",
      "Ser facial pentru ten gras",
      "Ser pentru conturul ochilor",
      "Tonic facial pentru ten uscat și sensibil",
      "Tonic facial revigorant pentru ten gras",
      "Ulei demachiant (Cleansing Oil)",
      "Balsam demachiant (Cleansing Balm)",
      "Săpun cu argilă roșie – Detoxifiere și revitalizare",
      "Exfoliant delicat pentru față",
      "Gel de față cu acid salicilic",
      "Mască gel cu acid hialuronic",
      "Elixir facial din trandafiri",
      "Spray facial cu aloe vera",
      "Mască pentru păr creț și ondulat",
    ],
    col2: [
      "Mască pentru păr drept și ușor ondulat",
      "Balsam cremos",
      "Balsam solid pentru păr creț și ondulat",
      "Balsam solid pentru păr ușor ondulat și drept",
      "Șampon solid pentru păr creț și ondulat",
      "Șampon solid pentru păr drept și ușor ondulat",
      "Șampon lichid",
      "Șampon cremos 2 în 1",
      "Șampon pentru copii",
      "Balsam fără clătire (Leave-In)",
      "Spray de păr cu protecție termică",
      "Ulei de păr",
      "Gel de păr",
      "Pomadă naturală pentru păr",
      "Spray hidratant de finisare",
      "Scrub pentru scalp",
      "Loțiune tonică pentru creșterea părului",
      "Ser pentru vârfuri despicate",
      "Parfum de păr",
      "Săpun intim natural",
      "Săpun natural de corp pentru copii",
      "Parfum lichid natural",
      "Parfum solid natural",
      "Pastă de dinți sub formă de gel",
      "Apă de gură",
      "Deodorant spray",
      "Unguent cu gălbenele",
      "Unguent cu arnică",
      "Balsam de buze hrănitor",
      "Ruj natural",
      "Exfoliant natural pentru buze",
      "Spray demachiant",
      "Spumă de ras",
      "Aftershave natural",
      "Cremă pentru mâini și picioare",
      "Gel de fixare pentru sprâncene",
      "Lumânare naturală pentru masaj",
      "Ser hrănitor pentru unghii și cuticule",
      "Repelent natural contra insectelor",
      "Săruri de baie revitalizante",
    ],
  },

  whatYouGet: {
    headline: "CE VEI DESCOPERI ÎN ACEST GHID COMPLET?",
    cta: "OBȚINE GHIDUL ACUM!",
    imageAlt: "Ce vei descoperi în ghid",
    items: [
      "Peste 80 de rețete testate și dovedite – inclusiv săpun cremă exfoliant, ulei uscat pentru față, spray de corp, protecție termică pentru păr și o varietate de formule noi.",
      "Baze pentru creme, geluri, șampoane și săpunuri – învață să creezi formule sigure și personalizate pentru orice tip de piele sau păr.",
      "Un ghid complet pas cu pas, pentru începători și avansați – asimilează totul, de la conceptele de bază la cele mai complexe tehnici.",
      "Catalogul ingredientelor – descoperă beneficiile diferitelor materii prime naturale pentru a crea produse cosmetice de înaltă performanță.",
      "Fitoterapie aplicată în cosmetologie – cum să folosești plantele medicinale pentru a potența efectul cosmeticelor tale.",
      "Secretele formulării naturale – reglarea pH-ului, conservarea, selecția materiilor prime și combinațiile eficiente.",
      "Sfaturi pentru producția de acasă sau profesională – creează-ți propriul atelier de cosmetice naturale și perfecționează-ți tehnicile.",
      "Sustenabilitate și grija pentru mediu – învață să creezi cosmetice biodegradabile și ecologice.",
    ],
  },

  testimonials: {
    headline: "VEZI CE SPUN OAMENII DESPRE GHIDUL DE COSMETICE NATURALE:",
    cta: "VREAU ACCES ACUM!",
    cards: [
      {
        name: "Maria S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Ador acest ghid! Am preparat deja crema de corp calmantă și săpunul de față, au ieșit incredibil. Mult mai bune decât produsele industriale pe care le foloseam înainte. Recomand cu mare drag!",
        source: "WhatsApp",
      },
      {
        name: "Elena G.",
        initials: "EG",
        color: "#0f766e",
        stars: 5,
        text: "Oameni buni, ce ghid minunat! Rețetele sunt super detaliate și ușor de urmat. Am vândut deja câteva produse prietenelor mele și le adoră. Face toți banii!",
        source: "WhatsApp",
      },
      {
        name: "Silvia R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Eram puțin sceptică înainte să-l cumpăr, dar a meritat din plin! Catalogul de materii prime m-a ajutat enorm să înțeleg ingredientele. Am făcut deja 6 rețete diferite și toate au ieșit impecabil.",
        source: "WhatsApp",
      },
      {
        name: "Daniela M.",
        initials: "DM",
        color: "#b45309",
        stars: 5,
        text: "Ce investiție grozavă! Cu acest ghid am învățat să fac șampon și balsam solid. Părul meu e mult mai sănătos și economisesc o grămadă de bani în fiecare lună. Vă mulțumesc!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Cu Ghidul de cosmetice naturale vei învăța să-ți creezi propriile produse cosmetice de la zero.",
    text2: "Îți arată pas cu pas cum să alegi ingredientele naturale, să adaptezi formulele pentru diverse tipuri de ten și păr și să-ți personalizezi produsele exact pe nevoile tale.",
    text3: "În plus, vei câștiga încredere și autonomie în formulare, putând testa și ajusta rețetele pentru a crea produse unice, cu propria lor identitate. Datorită catalogului detaliat de materii prime naturale, vei cunoaște cele mai bune ingrediente și vei descoperi combinația ideală pentru fiecare produs cosmetic.",
    cta: "OBȚINE GHIDUL ACUM!",
    imageAlt: "Independență în cosmetica naturală",
  },

  benefitsList: {
    headline: "Independență și creativitate în cosmetica naturală!",
    cta: "VREAU ACCES ACUM!",
    items: [
      {
        bold: "Învață să creezi",
        rest: " creme, seruri, șampoane, săpunuri și multe altele.",
      },
      {
        bold: "Descoperă cum să alegi",
        rest: " ingredientele potrivite pentru fiecare nevoie.",
      },
      {
        bold: "Eliberează-te de cosmeticele industriale și",
        rest: " dezvoltă-ți formule personalizate.",
      },
      {
        bold: "Pătrunde în lumea fitoterapiei aplicate în cosmetologie,",
        rest: " profitând de proprietățile terapeutice ale plantelor medicinale.",
      },
      {
        bold: "Redu costurile,",
        rest: " creându-ți propriile cosmetice fără a face rabat de la calitate.",
      },
      {
        bold: "Ai acces la formule profesionale",
        rest: " și învață să prepari în siguranță cele mai bune produse.",
      },
      {
        bold: "Evidențiază-te pe piața de frumusețe naturală,",
        rest: " care este în plină expansiune și prețuiește produsele sustenabile.",
      },
      {
        bold: "Învață cum să-ți amenajezi un atelier cosmetic acasă,",
        rest: " cu sfaturi practice pentru organizarea spațiului de lucru.",
      },
    ],
  },

  economy: {
    headline: "Economii și oportunitate de afaceri pe piața produselor naturale!",
    text1: "A-ți crea propriile cosmetice naturale reprezintă o oportunitate excelentă atât pentru a economisi, cât și pentru a porni o afacere. Cu Ghidul de cosmetice naturale înveți să produci cosmetice de înaltă calitate la un cost redus, evitând prețurile exagerate ale produselor convenționale și investind în ingrediente naturale, accesibile și eficiente.",
    text2: "Dacă vrei să-ți deschizi o afacere, acesta este un ghid prețios pentru a construi un proiect sustenabil și profitabil. Cu formule exclusive și sfaturi practice despre conservare, ambalare și piață, îți poți lansa propria marcă de cosmetice naturale, oferind produse artizanale care se aliniază tendinței de consum conștient și ecologic.",
    cta: "OBȚINE GHIDUL ACUM!",
    imageAlt: "Afacere pe piața produselor naturale",
  },

  finalCta: {
    urgencyLabel: "ULTIMA ZI DE COMANDĂ",
    urgencySub: "la preț promoțional!",
    urgencyText:
      "Este ultima ta șansă să profiți de oferta noastră specială și să devii parte din comunitatea noastră cu mii de cursante fericite!",
    offerPrice: "35 lei",
    button: "IA-ȚI ACCESUL ACUM!",
    productTitle: "Ghid de cosmetice naturale!",
    imageAlt: "Ghid de cosmetice naturale",
    bundleList: [
      "80 de rețete de cosmetice naturale",
      "Material de studiu complet",
      "Catalog educativ de materii prime",
      "Comunitate de cursante",
      "Suport dedicat pentru întrebări",
      "Listă de furnizori",
    ],
    timerLabels: {
      days: "Zile",
      hours: "Ore",
      minutes: "Minute",
      seconds: "Secunde",
    },
  },

  footer: {
    tagline: "Descoperă cum să creezi cosmeticele naturale perfecte!",
    linkLabel: "Curs complet de cosmetice naturale",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};